@startuml
    package UI {
        note "The UI layer is responsible for rendering\n the information and visualizing it for the user." as N1
    }
    package Calendar {
        note "The calendar and all its corresponding parts like\n events and appointments." as N2

        abstract class CalendarEvent {
            # String name
        }

        class Appointment extends CalendarEvent {
            - Date startDate
            - Date endDate
            - RepetitionRule repetitionRule
        }

        class Task extends CalendarEvent {
            - Duration duration
            - boolean splittable
            - Date timeSpanStart
            - Date timeSpanEnd
        }

        class Blocker extends CalendarEvent {
            - Duration duration
            - boolean splittable
            - Date timeSpanStart
            - Date timeSpanEnd
            - RepetitionRule repetitionRule
        }

        class Duration {
            - int days
            - int hours
            - int minutes
        }

        enum RepetitionRule {
            ONCE,
            EVERY_DAY,
            EVERY_WEEKDAY,
            WEEKEND
        }
    }
    package Logic {
        note "Contains the automatic organizing logic" as N3
    }
    package Services {
        note "Contains additional services that extend the basic functionality." as N4
        package "Google Calendar access" {
        }
        package ".csv export" {
        }
    }
@enduml